spring:
  application:
    name: gateway-service-ms
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: lb://user-ms
          predicates:
            - Path=/user-ms/**
          filters:
            - StripPrefix=1
        - id: post-route
          uri: lb://post-ms
          predicates:
            - Path=/post-ms/**
          filters:
            - StripPrefix=1
        - id: comment-route
          uri: lb://comment-ms
          predicates:
            - Path=/comment-ms/**
          filters:
            - StripPrefix=1
        - id: like-route
          uri: lb://like-ms
          predicates:
            - Path=/like-ms/**
          filters:
            - StripPrefix=1
        - id: friendship-route
          uri: lb://friendship-ms
          predicates:
            - Path=/friendship-ms/**
          filters:
            - StripPrefix=1
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://microeureka:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: false
    hostname: micro-api-gateway
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 10s
  retry:
    instances:
      default:
        maxAttempts: 2
        waitDuration: 200ms
