version: "3.9"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: perf_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./scripts/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - tcc-network

  grafana:
    image: grafana/grafana:latest
    container_name: perf_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - tcc-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: perf_node_exporter
    ports:
      - "9100:9100"
    networks:
      - tcc-network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: perf_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - tcc-network

networks:
  tcc-network:
    external: true
